before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.3/bin/
language: java
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - casperjs --version
  - echo Hello from DUT INFO Blagnac
  - ls -alF
  - cd sprint_5
  - echo COMPILATION des executables
  - ls -alF src
  - javac -encoding iso-8859-1 -cp .:./tools/junit.jar:./bin/ -d ./bin/ ./src/*.java
  - echo COMPILATION des modeles
  - ls -alF src/model
  - javac -cp .:./bin/ -d ./bin/ ./src/model/*.java
  - echo EXECUTION de l\'application
  - cd ./bin
  - java -cp .;.. MakeOPTIweb
  - echo EXECUTION des tests
  - ls -alF .
  - java -cp .:./bin:../tools/junit.jar LibCSVTest
  - java -cp .:./bin:../tools/junit.jar MakeOPTIwebTest
  - cd ..
  - echo COMPILATION des diagrammes de classes
  - java -jar ./tools/plantuml.jar -o images ./srcdoc/default.puml
  - java -jar ./tools/plantuml.jar -o images ./srcdoc/model.puml
  - ls -alF srcdoc/images
  - echo COMPILATION des documentations
  - python ./tools/asciidoc-8.6.9/asciidoc.py -a iconsdir=../tools/asciidoc-8.6.9/images -o ./doc/docUtilisateur.html ./srcdoc/docUtilisateur.txt
  - python ./tools/asciidoc-8.6.9/asciidoc.py -a iconsdir=../tools/asciidoc-8.6.9/images -o ./doc/docTechnique.html ./srcdoc/docTechnique.txt
  - ls -alF doc
  
  - cd ./OPTIweb/test
  - cp ../OPTIweb.html /tmp/OPTIweb.html
  - casperjs test casperAccueil.js