'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------
@startuml
'-----------------------------------
title <b>OPTI</b> class diagram

class LibCSV {
	ecrire()
	lire()
}

'-----------------------------------
@enduml
'-----------------------------------
