'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------
@startuml
'-----------------------------------

package MODEL {
}

class libSCV {
	ecrire()
	lire()
}

class MakeOPTIweb {
	
}

class Transform {
	CSVtoETU()
	ETUtoHTML()
}

'-----------------------------------
@enduml
'-----------------------------------
