'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------
@startuml
'-----------------------------------

package MODEL {
}

package VUE {
}

package CONTROLEUR {
}

'-----------------------------------
@enduml
'-----------------------------------
